# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery', '0015_auto_20170617_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightgallery',
            name='gallery_container_classes',
            field=models.CharField(blank=True, help_text='Additional classes to add to the div that wraps the page gallery, separated by spaces', max_length=255, verbose_name='Page Thumb Container Classes (optional)'),
        ),
        migrations.AddField(
            model_name='lightgallery',
            name='thumbnails_per_row',
            field=models.PositiveIntegerField(default=2, help_text='Thumbnails per row (on all screens if no other size is specified)', verbose_name='Thumbnails Per Grid Row (Base)'),
        ),
        migrations.AddField(
            model_name='lightgallery',
            name='thumbnails_per_row_lg',
            field=models.PositiveIntegerField(blank=True, help_text='Thumbnails per row on screens >= 992px', null=True, verbose_name='Thumbnails Per Grid Row (Large screens)'),
        ),
        migrations.AddField(
            model_name='lightgallery',
            name='thumbnails_per_row_md',
            field=models.PositiveIntegerField(blank=True, help_text='Thumbnails per row on screens >= 768px', null=True, verbose_name='Thumbnails Per Grid Row (Medium screens)'),
        ),
        migrations.AddField(
            model_name='lightgallery',
            name='thumbnails_per_row_sm',
            field=models.PositiveIntegerField(blank=True, help_text='Thumbnails per row on screens >= 576px', null=True, verbose_name='Thumbnails Per Grid Row (Small screens)'),
        ),
        migrations.AddField(
            model_name='lightgallery',
            name='thumbnails_per_row_xl',
            field=models.PositiveIntegerField(blank=True, help_text='Thumbnails per row on screens >= 1200px', null=True, verbose_name='Thumbnails Per Grid Row (Extra Large screens)'),
        ),
    ]
