# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery', '0017_auto_20180827_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightgallery',
            name='thumbnail_orientation',
            field=models.CharField(choices=[['v', 'Vertical'], ['h', 'Horizontal (text on right)'], ['hr', 'Horizontal (text on left)'], ['c', 'Columns']], default='v', max_length=2, verbose_name='Orientation of thumbnail elements'),
        ),
    ]
